## False News Prediction

### Predicting whether news article is reliable or unreliable

In [1]:
#Importing the required libraries
import pandas as pd
import numpy as np


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/MyDrive/False_news_data/train.csv')

In [4]:
df.shape

(20800, 5)

In [5]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [6]:
#Dropping the missing values
df.dropna(inplace=True)

In [7]:
df.shape

(18285, 5)

In [8]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [9]:
messages = df.copy()

In [10]:
messages.reset_index(drop=True,inplace=True)

In [11]:
messages.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [12]:
messages['title'][8]

'Obama’s Organizing for Action Partners with Soros-Linked ‘Indivisible’ to Disrupt Trump’s Agenda'

In [13]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [14]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [15]:
corpus[8]

'obama organ action partner soro link indivis disrupt trump agenda'

## Using Bag of Words for creating word vectors

In [16]:
#TFIDF Vectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,ngram_range=(1,3))
X = cv.fit_transform(corpus).toarray()

In [17]:
X.shape  

(18285, 5000)

In [18]:
y = messages['label']

In [19]:
y.shape

(18285,)

In [20]:
#Splitting the data for train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=0)

In [21]:
print(X_train.shape)  #all are numpy arrays
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(12799, 5000)
(12799,)
(5486, 5000)
(5486,)


In [23]:
cv.get_feature_names()[:100]

['abandon',
 'abc',
 'abc news',
 'abduct',
 'abe',
 'abedin',
 'abl',
 'abort',
 'abroad',
 'absolut',
 'abstain',
 'absurd',
 'abus',
 'abus new',
 'abus new york',
 'academi',
 'accept',
 'access',
 'access pipelin',
 'access pipelin protest',
 'accid',
 'accident',
 'accord',
 'account',
 'accus',
 'accus trump',
 'achiev',
 'acknowledg',
 'acknowledg emf',
 'acknowledg emf damag',
 'aclu',
 'acquit',
 'acquitt',
 'acr',
 'across',
 'act',
 'act like',
 'act new',
 'act new york',
 'action',
 'activ',
 'activist',
 'actor',
 'actual',
 'ad',
 'adam',
 'add',
 'addict',
 'address',
 'adhd',
 'admin',
 'administr',
 'admir',
 'admit',
 'adopt',
 'adult',
 'advanc',
 'advertis',
 'advic',
 'advis',
 'advis new',
 'advis new york',
 'advisor',
 'advoc',
 'affair',
 'affect',
 'affili',
 'affirm',
 'afford',
 'afghan',
 'afghanistan',
 'africa',
 'african',
 'african american',
 'ag',
 'age',
 'age new',
 'age new york',
 'agenc',
 'agenda',
 'agenda breitbart',
 'agent',
 'aggress',
 '

In [24]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [26]:
count_df = pd.DataFrame(X_train,columns= cv.get_feature_names())

In [27]:
count_df.head()

abandon  abc  abc news  abduct  ...  zone new york  zoo  zu  zuckerberg
0        0    0         0       0  ...              0    0   0           0
1        0    0         0       0  ...              0    0   0           0
2        0    0         0       0  ...              0    0   0           0
3        0    0         0       0  ...              0    0   0           0
4        0    0         0       0  ...              0    0   0           0

[5 rows x 5000 columns]

### MultinomialNB Algorithm

In [28]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import itertools

In [29]:
classifier = MultinomialNB()
classifier.fit(X_train,y_train)
pred = classifier.predict(X_test)
score_train = classifier.score(X_train,y_train)
score = metrics.accuracy_score(y_test,pred)
print('Train accuracy:  %0.3f' % score_train)
print('Test accuracy:  %0.3f' % score)
cm = metrics.confusion_matrix(y_test,pred)
cm

Train accuracy:  0.924
Test accuracy:  0.902


array([[2768,  316],
       [ 223, 2179]])

### Multinomial Classifier with Hyperparameter

In [30]:
classifier = MultinomialNB(alpha=0.1)


In [31]:
previous_score = 0
for alpha in np.arange(0,1,0.1):
  sub_classifier = MultinomialNB(alpha=alpha)
  sub_classifier.fit(X_train,y_train)
  y_pred = sub_classifier.predict(X_test)
  score = metrics.accuracy_score(y_test,y_pred)
  if score > previous_score:
    classifier = sub_classifier
  print('Alpha: {}, Score: {}'.format(alpha,score))

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:507: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)


Alpha: 0.0, Score: 0.8904484141450966
Alpha: 0.1, Score: 0.9030258840685381
Alpha: 0.2, Score: 0.9030258840685381
Alpha: 0.30000000000000004, Score: 0.9026613197229311
Alpha: 0.4, Score: 0.9019321910317171
Alpha: 0.5, Score: 0.9024790375501276
Alpha: 0.6000000000000001, Score: 0.9028436018957346
Alpha: 0.7000000000000001, Score: 0.9035727305869486
Alpha: 0.8, Score: 0.9030258840685381
Alpha: 0.9, Score: 0.9032081662413416


alpha = 0.7 gives the best accuracy model.

In [32]:
#Getting Features names
feature_names = cv.get_feature_names()

In [33]:
 classifier.coef_[0]

array([ -9.13851551,  -8.66088795,  -9.13851551, ..., -10.83311123,
        -8.7962293 ,  -9.36677416])

In [34]:
### Most real
sorted(zip(classifier.coef_[0], feature_names), reverse=True)[:20]

[(-3.9920894686099926, 'trump'),
 (-4.283778449404154, 'hillari'),
 (-4.375295545839294, 'clinton'),
 (-4.8873997935153906, 'elect'),
 (-5.144630412704637, 'new'),
 (-5.239226293337629, 'comment'),
 (-5.272857037363478, 'video'),
 (-5.400360096919867, 'war'),
 (-5.400360096919867, 'us'),
 (-5.400360096919867, 'hillari clinton'),
 (-5.434948525093684, 'fbi'),
 (-5.450146386003116, 'vote'),
 (-5.535349569997123, 'email'),
 (-5.592540682275724, 'world'),
 (-5.628494225203827, 'obama'),
 (-5.717782305845059, 'donald'),
 (-5.751706861626975, 'donald trump'),
 (-5.7656056260177895, 'russia'),
 (-5.868713801008469, 'day'),
 (-5.868713801008469, 'america')]

In [35]:
### Most Unreal
sorted(zip(classifier.coef_[0], feature_names))[:5000]

[(-10.833111226611438, 'abe'),
 (-10.833111226611438, 'abroad'),
 (-10.833111226611438, 'abus new'),
 (-10.833111226611438, 'abus new york'),
 (-10.833111226611438, 'act new'),
 (-10.833111226611438, 'act new york'),
 (-10.833111226611438, 'advic'),
 (-10.833111226611438, 'advis new'),
 (-10.833111226611438, 'advis new york'),
 (-10.833111226611438, 'age new'),
 (-10.833111226611438, 'age new york'),
 (-10.833111226611438, 'agenda breitbart'),
 (-10.833111226611438, 'ail'),
 (-10.833111226611438, 'aleppo new'),
 (-10.833111226611438, 'aleppo new york'),
 (-10.833111226611438, 'ali'),
 (-10.833111226611438, 'america breitbart'),
 (-10.833111226611438, 'america new york'),
 (-10.833111226611438, 'american breitbart'),
 (-10.833111226611438, 'american new'),
 (-10.833111226611438, 'american new york'),
 (-10.833111226611438, 'ami'),
 (-10.833111226611438, 'ami schumer'),
 (-10.833111226611438, 'amp'),
 (-10.833111226611438, 'applaud'),
 (-10.833111226611438, 'arson'),
 (-10.83311122661143

## Logistic Regression


In [36]:
from sklearn.linear_model import LogisticRegression

In [37]:
def model_fit(classifier,X,y,x_cv,y_cv):
  classifier.fit(X,y)
  pred = classifier.predict(x_cv)
  score_train = classifier.score(X,y)
  score = metrics.accuracy_score(y_cv,pred)
  print('Train accuracy: %0.3f' % score_train)
  print('Test accuracy: %0.3f' % score)
  cm = metrics.confusion_matrix(y_cv,pred)
  return cm

In [38]:
clf = LogisticRegression()
model_fit(clf,X_train,y_train,X_test,y_test)

Train accuracy: 0.976
Test accuracy: 0.934


array([[2799,  285],
       [  76, 2326]])

## Support vector classifier

In [39]:
from sklearn.svm import SVC

In [40]:
clf2 = SVC(kernel='linear')
model_fit(clf2,X_train,y_train,X_test,y_test)

Train accuracy: 0.990
Test accuracy: 0.926


array([[2835,  249],
       [ 156, 2246]])

## PassiveAggresive Classifier

In [41]:
from sklearn.linear_model import PassiveAggressiveClassifier

In [42]:
passive = PassiveAggressiveClassifier()
model_fit(passive,X_train,y_train,X_test,y_test)

Train accuracy: 1.000
Test accuracy: 0.917


array([[2831,  253],
       [ 202, 2200]])